version: "3"
services:
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000

  rbbackend:
    build: ./rbbackend
    volumes:
      - ./rbbackend/:/app
      - /app/vendor
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
