version: "3"
services:
  rbbackend:
    build: ./rbbackend
    volumes:
      - ./rbbackend/:/app
      - /app/vendor
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
