version: "3"
services:
  frontend:
    build: ./frontend
    user: "${UID}:${GID}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000

  rbbackend:
    build: ./rbbackend
    user: "${UID}:${GID}"
    volumes:
      - ./rbbackend/:/app
      - /app/vendor
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    depends_on:
      - db

volumes:
  pgdata: